use_frameworks!

target 'RxEventHub_Tests' do
  pod 'RxEventHub', :path => '../'
  
  pod 'Quick', '1.2.0'
  pod 'Nimble', '7.0.3'
  pod 'RxSwift', '3.6.1'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
